CREATE DATABASE DB_TWITTER

CREATE TABLE USUARIOS(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(32) NOT NULL
);

CREATE TABLE POSTS(
	ID INT(11) PRIMARY KEY AUTO_INCREMENT,
	ID_USUARIO INT,
	DATA_POST DATETIME,
	MENSAGEM TEXT,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);
